### ISSUE TITLE
Cannot succeed in "Test Audio Transmission"

### ISSUE THREAD

**Issue by dogos1** [slinga-homebrew/Save-Game-Extractor#4]
I tried to transfer savedata in internal sega saturn memory to PC.
So I firstly run below command in Lubuntu's terminal 
`minimodem -R 44100 -r 1200 --sync 0xAB --stopbits 4 --startbits 4`
then I Boot off my saturn with burn SGEX CD and select the "Test Audio Transmission" option in SGEX screen.
and finally press C button to play the string`This is CooL`

But It display nothing in lubuntu's terminal..

I even checked several times that line In jack is surely plugged in with saturn's Audio Composite jack(red and white jack) and It surely displayed in Lubuntu's volume control panel that Port of Line In is plugged in on the Input device tab.
But It doesn't display anything When select the "Test Audio Transmission" and Press C button in SGEX screen ...

https://ibb.co/BjSsPLN
https://ibb.co/SPnjjqT
https://ibb.co/pn9sWbS

It there any way to solve my problem..?

**Comment by slinga-homebrew** [comment]
Can you try recording to wav file as a test? Without minimodem? My best guess is it's receiving the audio for some reason.

**Comment by dogos1** [comment]
> Can you try recording to wav file as a test? Without minimodem? My best guess is it's receiving the audio for some reason.
How can I record to wav file from line in port which is connected with av composite jack of saturn?

**Comment by slinga-homebrew** [comment]
Some things you can try to debug:
1) Verify when plugged into your TV you can hear SGEX making noise. You can use the "This is cool" test. This is to verify your Saturn is outputting audio. 
2) You can use "Audio Recorder" on Ubuntu (https://itsfoss.com/record-streaming-audio/) to record from line in. I would verify that it is receiving audio. It might be you are selecting the incorrect recording device? My guess is the problem is at this step. 
3) Once you are able to record to a file you can use minimodem's -f option to work on a file. 

Let me know if that helps.

**Comment by dogos1** [comment]
I have used Y-cable of below screenshot which is very common in my country.
https://i.ibb.co/1rqfBL3/20210403-011945-1.jpg
Today,I went to big city and visit a store specializing in Cable/adaptor where I brought Y-cable of below screenshot
https://i.ibb.co/6t1HVr9/20210403-012000-1.jpg

And I test extracting saturn's save with it and I works very well! and It even works in cygwin64 circumstance.
It takes approximatively 10-15 min to transfer all of save data(total size is 3.2kilo byte) from saturn to PC.
and all of raw bin file successfully converted to bup files.
It is really awesome.I really admire your genius application...It is very powerful and essencial(Y-cable) equipment very cheap($2 in my country)!It work still more fantastic than Saturn Floppy Drive which is very expensive.
But..I really want you to add an option of SGEX menu which is to extract whole savefile as one compressed image file. Because It is quite inconvenient to type each name(title) of savedata on keyboard in order to save each savefile to pc. I have to check more than 10 name(title) of savedata in SGEX's screen and type as it i, checking and typing name(title) takes more than 10min..I really want to make one compressed file which automatically write each name(title) of savedata in saturn's internal ram.

**Comment by slinga-homebrew** [comment]
I'm glad you were able to get it to work. ss-save-parser is a good tool. If you ever want to get your saves back to Saturn, use https://github.com/slinga-homebrew/save-game-copier. You can insert your custom saves into the ISO. 

Regarding additional features, I don't plan to update SGEX anymore. I do appreciate your suggestion though.
