### ISSUE TITLE
"too small" message appears, but data is OK

### ISSUE THREAD

**Issue by eddebaby** [slinga-homebrew/Save-Game-Extractor#5]
I have been copying Shining Force 3 Scenario 1 saves from my Saturn, both official backup cartridge and internal RAM, and about every 1 in 10 saves:

- seem to complete data transfer
- generate a valid .BUP file
- the save data can be loaded by a real Saturn/emulator... 
- but the "What the heck, too small" message appears in Save Game Extractor at the end of the transfer.

I have been ignoring the "too small" message in these cases, as it appears to be spurious. 

I can provide examples of save data that produces this message, if required.

**Comment by slinga-homebrew** [comment]
I updated the error message to say "possible error" instead of "what the heck". I don't remember why I had that check...

I've seen it before but it still works. I use MD5 to verify that the save was transferred correctly so this shouldn't be an issue.
