### ISSUE TITLE
SGEX disc not booting on Japanese Saturn

### ISSUE THREAD

**Issue by hikari62** [slinga-homebrew/Save-Game-Extractor#9]
I'm having trouble getting sgex disc to boot on my Saturn. I burned the sgex.iso onto a CD-R and it boots properly when I tested it in Yabause, but when I load it onto my saturn I get the error "disc unsuitable for this system." I have a Japanese Saturn, model 1 I believe. Any idea why it's not working? Thanks!

**Comment by slinga-homebrew** [comment]
How are do you boot burned discs? Are you using Pseudo Saturn Kai, modchip, swap trick, etc?

Maybe you didn't burn it correctly? Did you say you could boot the burned disc in Yabause?

**Comment by hikari62** [comment]
I guess I didn't realize I had to force it to boot, the instructions just said to boot it up, but makes sense. I don't have a pseudo saturn kai or a modchip, but I have original japanese game discs I could try the swap trick with. 

It seems to have been burned properly, the program boots on Yabause without issue.

**Comment by slinga-homebrew** [comment]
I added a note to the README about requiring a modchip or other device to boot. 

Swap trick isn't too hard. Best of luck.
